### ISSUE TITLE
Is there any format converting on corpus (like the step 1 in general distillation in original TinyBERT repo)?

### ISSUE THREAD

**Issue by janezzzz** [Lisennlp/TinyBert#2]
# Is there any format converting on corpus (like step 1 of general distillation in the original TinyBERT repo)?

${BERT_BASE_DIR}$ includes the BERT-base teacher model.
 
python pregenerate_training_data.py --train_corpus ${CORPUS_RAW} \ 
                  --bert_model ${BERT_BASE_DIR}$ \
                  --reduce_memory --do_lower_case \
                  --epochs_to_generate 3 \
                  --output_dir ${CORPUS_JSON_DIR}$ 

I'm a little bit confused with this part, shall I download some pre-trained BERT model and the corpus at the beginning? And it seems this part is not included in your script. Is there any difference? Thx.

**Comment by Lisennlp** [comment]
Yes, my own library takes out the corpus and the model download section, requiring you to download the Corpus and the pre-trained model in advance. The goal is to make it easy for people to use their own corpus and enhance it.
