### ISSUE TITLE
Can I use it to distill roberta? 

### ISSUE THREAD

**Issue by Tweakzx** [Lisennlp/TinyBert#3]
I used it to distill a roberta model, but there are some errors the may be "out of the index" thing?I am confused if tinybert can distill roberta? Hope you help me .

  /opt/conda/conda-bld/pytorch_1565272279342/work/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [47,0,0], thread: [63,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

**Comment by Lisennlp** [comment]
Yes, your problem should be that your data length exceeds Bert’s position limit of 512.
