### ISSUE TITLE
蒸馏后的模型推理速度是否提升

### ISSUE THREAD

**Issue by qdchenxiaoyan** [Lisennlp/TinyBert#6]
Excuse me, after the author uses the enhanced training set to distill, does the inference speed increase by 8 times as fast as the paper said? My test found that the single line is basically the same as the bert base, and the batch processing changes linearly, which is not as fast as the bert base. I wonder if the author knows the reason? Thank you for the answer.
请问一下，作者在使用增强训练集蒸馏完之后，推理速度有没有提升论文中说的快8倍？我测试发现单条跟bert base基本一致，批处理大体线性变化，还不如bert base快，不知作者是否知道是什么原因？谢谢解答。

**Comment by Lisennlp** [comment]
我不太清楚你怎么测试的时间，但是我要说的是，论文说的时间，仅仅指的是从进入网络到出来这一个过程，你说单条数据时间差不多，理论上来看是不应该的，我估计是因为你把数据处理，时间算进去了，因为单条数据而言，bert base和tinybert都很快，可能主要花的时间在数据加载上面。
