### ISSUE TITLE
训练步骤请教

### ISSUE THREAD

**Issue by ysujiang** [Lisennlp/TinyBert#7]
训练过程中的2.用相关任务的数据对Bert进行fine-tune得到fine-tune的Bert base模型；请问这一步是在训练中的哪些步骤中体现的呀，感谢回复

**Comment by Lisennlp** [comment]
> 训练过程中的2.用相关任务的数据对Bert进行fine-tune得到fine-tune的Bert base模型；请问这一步是在训练中的哪些步骤中体现的呀，感谢回复

你说的这步是正常的模型fine-tune过程（这个用原始bert代码进行训练就行了的，只是换个数据集），这个代码只针对蒸馏过程。
