### ISSUE TITLE
中文数据增强

### ISSUE THREAD

**Issue by ysujiang** [Lisennlp/TinyBert#8]
hi，蒸馏过程中，用做数据增强吗？数据增强会提高分类任务的精度吗？

**Comment by Lisennlp** [comment]
论文是在finetune过程中采用的数据增强，至于数据增强是否会提高分类任务的精度，理论上是可以的。

> hi，蒸馏过程中，用做数据增强吗？数据增强会提高分类任务的精度吗？

**Comment by ysujiang** [comment]
> 

基于下游任务和论文里的方法自己做蒸馏，和基于公开的general tinybert模型+下游任务，两者的结果有差异吗？

**Comment by Lisennlp** [comment]
> 于下游任务和

没对比过 不太清楚
